### ISSUE TITLE
Username must not be null!

### ISSUE THREAD

**Issue by Un1q32** [fnuecke/sedna-cli#1]
what do i do?

**Comment by ja2142** [comment]
If you mean gradle complaining about null username when trying to download dependencies: for the time being it seems like you need an access token to get github hosted gradle packages. To get it to work, I've generated github public access token, and put it in `~/.gradle/gradle.properties` along with username:
```
gpr.user=ja2142
gpr.key=<github_pat>
```
There's also an option to use `GPR_USER` and `GPR_KEY` environment variables instead.

**Comment by Un1q32** [comment]
I don't remember making this issue, I have no idea what it was about
